### ISSUE TITLE
Web Server example only works one time

### ISSUE THREAD

**Issue by alfredomova** [sparkfun/WiFly-Shield#43]
after receiving the http response , if you try to do a second request it does respond, and it won't response until you reboot it,

![first](https://cloud.githubusercontent.com/assets/2198158/19246270/15675d82-8eeb-11e6-98b1-8e01c9c09b93.PNG)

![second](https://cloud.githubusercontent.com/assets/2198158/19246271/156990b6-8eeb-11e6-966c-cf3acb4a184e.PNG)

**Comment by santaimpersonator** [comment]
I am closing this issue to clean up our repositories. This is primarily due to the fact that this issue was filed 3 years ago, we have since retired this product, and support for this issue should go to the [forum](https://forum.sparkfun.com/) anyway (*doesn't appear to be part of hookup guide example code*). **Please, feel free to repost this issue to the forum if needed.**
